name: Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  deploy-auth:
    runs-on: ubuntu-latest
    environment: auth
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: ${{ github.run_id }}
          aws-region: us-east-2
      - run: npm ci
      - run: npm run cdk deploy TailscaleAuthKey
      - run: aws secretsmanager put-secret-value --secret-id tailscale/casa-cirrus-auth-key --secret-string "$TS_AUTHKEY"
        env:
          TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}
  deploy-policy:
    runs-on: ubuntu-latest
    environment: tailnet
    steps:
      - uses: actions/checkout@v6
      - uses: tailscale/gitops-acl-action@v1
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tailnet: ${{ secrets.TS_TAILNET }}
          action: apply
  deploy-exit:
    needs: [ deploy-auth, deploy-policy ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [ us-east-1, us-west-2 ]
    environment: ${{ matrix.region }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: ${{ github.run_id }}
          aws-region: ${{ matrix.region }}
      - run: npm ci
      - run: npm run cdk deploy TailscaleExitNode
      - name: Force Tailscale ECS Service Redeployment
        run: |
          CLUSTER_ARN=$(aws cloudformation list-stack-resources --stack-name TailscaleExitNode --query "StackResourceSummaries[?ResourceType=='AWS::ECS::Cluster'].PhysicalResourceId | [0]" --output text)
          SERVICE_ARN=$(aws cloudformation list-stack-resources --stack-name TailscaleExitNode --query "StackResourceSummaries[?ResourceType=='AWS::ECS::Service'].PhysicalResourceId | [0]" --output text)
          aws ecs update-service --cluster "$CLUSTER_ARN" --service "$SERVICE_ARN" --force-new-deployment
  deploy-router:
    needs: [ deploy-auth, deploy-policy, deploy-exit ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [ us-east-2 ]
    environment: ${{ matrix.region }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: ${{ github.run_id }}
          aws-region: ${{ matrix.region }}
      - run: npm ci
      - run: npm run cdk deploy TailscaleRouterNode
      - name: Force Tailscale ECS Service Redeployment
        run: |
          CLUSTER_ARN=$(aws cloudformation list-stack-resources --stack-name TailscaleRouterNode --query "StackResourceSummaries[?ResourceType=='AWS::ECS::Cluster'].PhysicalResourceId | [0]" --output text)
          SERVICE_ARN=$(aws cloudformation list-stack-resources --stack-name TailscaleRouterNode --query "StackResourceSummaries[?ResourceType=='AWS::ECS::Service'].PhysicalResourceId | [0]" --output text)
          aws ecs update-service --cluster "$CLUSTER_ARN" --service "$SERVICE_ARN" --force-new-deployment
